apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: es-cluster
spec:
  version: "${ENGINE_VERSION}"
  http:
    service:
      spec:
        type: ClusterIP
  nodeSets:
    - name: default
      count: ${WORKER_COUNT}
      podTemplate:
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: elasticsearch-nodepool
          initContainers:
            - name: sysctl
              securityContext:
                privileged: true
                runAsUser: 0
              command: ["sh", "-c", "sysctl -w vm.max_map_count=262144"]
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: "${MEMORY_REQUEST}"
                  cpu: "${CPU_REQUEST}"
                limits:
                  memory: "${MEMORY_LIMIT}"
                  cpu: "${CPU_LIMIT}"
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            storageClassName: "${STORAGE_CLASS_NAME}"
            resources:
              requests:
                storage: "${STORAGE_SIZE}"
