# Operational settings (gke-connect, stack-status, stack-access)
GKE_CLUSTER_NAME := qdrant-benchmark

# Timeout configuration for k8s-wait-ready
KUBECTL_WAIT_TIMEOUT ?= 600s

STACK_ENGINE_LABEL := Qdrant

ENGINE_POD_SELECTOR := app=qdrant
SERVICE_NAMES := qdrant-service qdrant-benchmark qdrant-headless

ENGINE_LOG_POD_SELECTOR := app=qdrant
UI_SERVICE_NAME := qdrant-service
UI_URL_TEMPLATE := URL:      https://$${EXTERNAL_IP}:6333/dashboard

.PHONY: ensure-qdrant-api-key-in-env k8s-apply k8s-apply-manifests _k8s-wait-ready k8s-delete-impl

ensure-qdrant-api-key-in-env:
	@set -euo pipefail; \
	GENERAL_SECRETS="$(REPO_ROOT)/shared/secrets/.secrets.env"; \
	QDRANT_KEY_FILE="$(STACK_DIR).qdrant-api-key.env"; \
	if [[ ! -f "$$GENERAL_SECRETS" ]]; then \
		echo >&2 "ERROR: $$GENERAL_SECRETS not found. Copy shared/secrets/.secrets.env.example to shared/secrets/.secrets.env and fill values."; \
		exit 1; \
	fi; \
	if [[ -f "$$QDRANT_KEY_FILE" ]] && grep -qE '^QDRANT_API_KEY=[^[:space:]]+' "$$QDRANT_KEY_FILE" 2>/dev/null; then \
		exit 0; \
	fi; \
	if grep -qE '^QDRANT_API_KEY=[^[:space:]]+' "$$GENERAL_SECRETS" 2>/dev/null; then \
		grep -E '^QDRANT_API_KEY=' "$$GENERAL_SECRETS" > "$$QDRANT_KEY_FILE"; \
		exit 0; \
	fi; \
	if ! command -v openssl >/dev/null 2>&1; then \
		echo >&2 "ERROR: openssl is required to generate QDRANT_API_KEY"; \
		exit 1; \
	fi; \
	KEY="$$(openssl rand -hex 32)"; \
	{ \
		echo "# Qdrant API key — synced to Kubernetes by make secrets-create"; \
		echo "# (generated by make ensure-qdrant-api-key-in-env; rotate with cluster if you rotate secrets)"; \
		echo "QDRANT_API_KEY=$$KEY"; \
	} > "$$QDRANT_KEY_FILE"

ENGINE_SECRET_PREREQS := ensure-qdrant-api-key-in-env
ENGINE_SOURCE_ENV := if [[ -f "$(STACK_DIR).qdrant-api-key.env" ]]; then set -a; source "$(STACK_DIR).qdrant-api-key.env"; set +a; fi; \

define ENGINE_EXTRA_SECRETS
	if [[ -z "$${QDRANT_API_KEY:-}" ]]; then \
		echo >&2 "ERROR: QDRANT_API_KEY is not set. Add engines/qdrant/.qdrant-api-key.env or run \`make ensure-qdrant-api-key-in-env\`."; \
		exit 1; \
	fi; \
	command -v openssl >/dev/null 2>&1 || { echo >&2 "ERROR: openssl is required for Qdrant TLS material"; exit 1; }; \
	if kubectl get secret qdrant-tls --namespace="$$NS" >/dev/null 2>&1; then \
		:; \
	else \
		TMP_TLS=$$(mktemp -d); \
		trap 'rm -rf "$$TMP_TLS"' EXIT; \
		{ echo '[req]'; echo 'distinguished_name = req_distinguished_name'; echo 'req_extensions = v3_req'; echo 'prompt = no'; echo ''; \
		  echo '[req_distinguished_name]'; echo 'CN = qdrant-benchmark.default.svc.cluster.local'; echo ''; \
		  echo '[v3_req]'; echo 'basicConstraints = CA:FALSE'; echo 'keyUsage = digitalSignature, keyEncipherment'; \
		  echo 'extendedKeyUsage = serverAuth'; echo 'subjectAltName = @alt_names'; echo ''; \
		  echo '[alt_names]'; echo 'DNS.1 = qdrant-benchmark.default.svc.cluster.local'; \
		  echo 'DNS.2 = qdrant-benchmark.default.svc'; echo 'DNS.3 = qdrant-service.default.svc.cluster.local'; \
		  echo 'DNS.4 = qdrant-headless.default.svc.cluster.local'; echo 'DNS.5 = localhost'; echo 'IP.1 = 127.0.0.1'; \
		} > "$$TMP_TLS/openssl.cnf"; \
		openssl req -x509 -newkey rsa:4096 -sha256 -days 3650 -nodes \
			-keyout "$$TMP_TLS/tls.key" -out "$$TMP_TLS/tls.crt" \
			-config "$$TMP_TLS/openssl.cnf" -extensions v3_req; \
		kubectl create secret tls qdrant-tls \
			--cert="$$TMP_TLS/tls.crt" \
			--key="$$TMP_TLS/tls.key" \
			--namespace="$$NS"; \
		trap - EXIT; \
		rm -rf "$$TMP_TLS"; \
	fi; \
	kubectl create secret generic qdrant-api-key \
		--from-literal=api-key="$$QDRANT_API_KEY" \
		--namespace="$$NS" \
		--dry-run=client -o yaml | kubectl apply -f -; \

endef

define ENGINE_CREDENTIALS_UPSERT
	kubectl create secret generic jingra-credentials \
		--from-literal=ENGINE_PASSWORD="$$QDRANT_API_KEY" \
		--namespace="$$NS" \
		--dry-run=client -o yaml | kubectl apply -f -; \

endef

define UI_CREDENTIAL_LINES
	ENGINE_PASSWORD=$$(kubectl get secret jingra-credentials -n $(NAMESPACE) -o jsonpath='{.data.ENGINE_PASSWORD}' 2>/dev/null | base64 -d); \
	echo "API key:  $$ENGINE_PASSWORD"; \

endef

k8s-apply: secrets-create k8s-apply-manifests _k8s-wait-ready

k8s-apply-manifests:
	$(KUBECTL_APPLY_K8S_FROM_VARS)

_k8s-wait-ready:
	@set -euo pipefail; \
	NS="$(or $(NAMESPACE),default)"; \
	kubectl rollout status statefulset/qdrant -n "$$NS" --timeout=$(KUBECTL_WAIT_TIMEOUT)

k8s-delete-impl:
	@kubectl delete job jingra-load jingra-eval -n $(NAMESPACE) --ignore-not-found
	@kubectl delete statefulset qdrant -n $(NAMESPACE) --ignore-not-found
	@kubectl delete pvc -l app=qdrant -n $(NAMESPACE) --ignore-not-found
	@kubectl delete -f $(STACK_DIR)k8s/ --ignore-not-found
