engine: "qdrant"

qdrant:
  url_env: "QDRANT_URL"
  api_key_env: "ENGINE_PASSWORD"
  vector_field: "embedding"
  grpc_timeout_seconds: 300
  query_dump_directory: ./query-dumps

dataset: "wiki-dpr-e5-768"

datasets:
  wiki-dpr-e5-768:
    type: "wiki-dpr-e5-768-knn"
    index_name: "wiki-dpr-e5-768"
    vector_size: 768
    distance: "cosine"
    schema_name: "wiki-dpr-e5-768-knn"
    query_name: "wiki-dpr-e5-768-knn"
    path:
      data_path: "datasets/wiki-dpr-e5-768/data.parquet"
      queries_path: "datasets/wiki-dpr-e5-768/queries.parquet"
      data_url_env: "DATASET_DATA_URL"
      queries_url_env: "DATASET_QUERIES_URL"
    data_mapping:
      id_field: "id"
      vector_field: "embedding"
    queries_mapping:
      query_vector_field: "embedding"
      ground_truth_field: "closest_ids"
    param_groups:
      recall@100:
        - { size: 100, hnsw_ef: 10, oversampling: 3 } # 0.8716
        - { size: 100, hnsw_ef: 50, oversampling: 3 } # 0.9327
        - { size: 100, hnsw_ef: 60, oversampling: 3 } # 0.9423
        - { size: 100, hnsw_ef: 70, oversampling: 3 } # 0.9492
        - { size: 100, hnsw_ef: 80, oversampling: 3 } # 0.9549
        - { size: 100, hnsw_ef: 90, oversampling: 3 } # 0.9592
        - { size: 100, hnsw_ef: 100, oversampling: 3 } # 0.9628
        - { size: 100, hnsw_ef: 150, oversampling: 3 } # 0.9628

load:
  threads: 4
  batch_size: 1000
  queue_capacity: 10

evaluation:
  warmup_workers: 4
  measurement_workers: 4
  warmup_rounds: 3
  measurement_rounds: 1

output:
  sinks:
    - type: "elasticsearch"
      config:
        url_env: "RESULTS_ES_URL"
        user_env: "RESULTS_ES_USER"
        password_env: "RESULTS_ES_PASSWORD"
        index: "jingra-results"
