#!/usr/bin/env bash
# Called from `make k8s-deploy` only. Ensures scripts/.qdrant-api-key.env exists with a stable
# QDRANT_API_KEY so create-k8s-secrets.sh can sync to Kubernetes without rotating keys every run.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
GENERAL_SECRETS="${REPO_ROOT}/secrets/.secrets.env"
QDRANT_KEY_FILE="${SCRIPT_DIR}/.qdrant-api-key.env"

if [[ ! -f "$GENERAL_SECRETS" ]]; then
  echo "ERROR: ${GENERAL_SECRETS} not found."
  echo "  cp secrets/.secrets.env.example secrets/.secrets.env  and fill Docker + dataset values first."
  exit 1
fi

if [[ -f "$QDRANT_KEY_FILE" ]] && grep -qE '^QDRANT_API_KEY=[^[:space:]]+' "$QDRANT_KEY_FILE" 2>/dev/null; then
  echo "✓ QDRANT_API_KEY already set in .qdrant-api-key.env"
  exit 0
fi

# Legacy: key lived in secrets/.secrets.env — migrate to dedicated file
if grep -qE '^QDRANT_API_KEY=[^[:space:]]+' "$GENERAL_SECRETS" 2>/dev/null; then
  echo "Migrating QDRANT_API_KEY from secrets/.secrets.env → .qdrant-api-key.env ..."
  grep -E '^QDRANT_API_KEY=' "$GENERAL_SECRETS" > "$QDRANT_KEY_FILE"
  echo "✓ Wrote ${QDRANT_KEY_FILE} (you may remove the QDRANT_API_KEY line from secrets/.secrets.env)"
  exit 0
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "ERROR: openssl is required to generate QDRANT_API_KEY"
  exit 1
fi

KEY="$(openssl rand -hex 32)"
{
  echo "# Qdrant API key — synced to Kubernetes by create-k8s-secrets.sh"
  echo "# (generated by ensure-qdrant-api-key-in-env.sh; rotate with cluster if you rotate secrets)"
  echo "QDRANT_API_KEY=${KEY}"
} > "$QDRANT_KEY_FILE"

echo "✓ Created ${QDRANT_KEY_FILE} (first k8s-deploy for this workspace)"
