apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: es-cluster
spec:
  version: "${engineVersion}"
  http:
    service:
      spec:
        type: LoadBalancer
  podTemplate:
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: kibana-nodepool
  count: 1
  elasticsearchRef:
    name: es-cluster
  config:
    xpack.security.session.idleTimeout: "7d"
    xpack.security.session.lifespan: "1Y"
