apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: es-cluster
spec:
  version: 9.3.2
  http:
    service:
      spec:
        type: ClusterIP
  nodeSets:
    - name: default
      count: 6
      podTemplate:
        spec:
          nodeSelector:
            cloud.google.com/gke-nodepool: elasticsearch-nodepool
          initContainers:
            - name: sysctl
              securityContext:
                privileged: true
                runAsUser: 0
              command: ["sh", "-c", "sysctl -w vm.max_map_count=262144"]
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: 56Gi
                  cpu: 15
                limits:
                  memory: 56Gi
                  cpu: 15
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            storageClassName: premium-rwo
            resources:
              requests:
                storage: 200Gi
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: es-cluster
spec:
  version: 9.3.2
  http:
    service:
      spec:
        type: LoadBalancer
  podTemplate:
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: kibana-nodepool
  count: 1
  elasticsearchRef:
    name: es-cluster
  config:
    xpack.security.session.idleTimeout: "7d"
    xpack.security.session.lifespan: "1Y"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jingra-connection
  namespace: default
data:
  ELASTICSEARCH_URL: "https://es-cluster-es-internal-http.default.svc.cluster.local:9200"
  ELASTICSEARCH_USER: "elastic"
