include $(REPO_ROOT)/shared/make/k8s-apply.mk
include $(REPO_ROOT)/shared/make/terraform.mk
include $(REPO_ROOT)/shared/make/gke-connect.mk
include $(REPO_ROOT)/shared/make/jingra-jobs.mk
include $(REPO_ROOT)/shared/make/logs-common.mk
include $(REPO_ROOT)/shared/make/stack-secrets.mk
include $(REPO_ROOT)/shared/make/stack-status.mk
include $(REPO_ROOT)/shared/make/stack-access.mk
include $(REPO_ROOT)/shared/make/k8s-delete.mk
